Change application from GAN to image-generation
deepjavalibrary/djl pull request #1048
Opened 2021-06-25 01:03 UTC by AzizZayed

## Description ##

Change the name of the application to show a problem such as Image Generation rather than a DL technique.

2021-06-25 20:02 UTC, zachgk approved these changes

2021-06-25 20:36 UTC, frankfliu commented
This file need to be updated as well: https://github.com/deepjavalibrary/djl/blob/master/pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/gan/ai/djl/pytorch/biggan-deep/metadata.json

It's location should also be moved to: pytorch/pytorch-model-zoo/src/test/resources/mlrepo/model/cv/image-generation/ai/djl/pytorch/biggan-deep/metadata.json

2021-06-25 20:39 UTC, frankfliu requested changes

2021-06-25 20:39 UTC, frankfliu commented on api/src/main/java/ai/djl/Application.java
> +        Application IMAGE_GENERATION = new Application("cv/image_generation");
We also need implement creation of IMAGE_GENERATION instance:
```
    public static Application of(String path) {
    }

```

2021-06-26 18:57 UTC, frankfliu approved these changes

2021-06-26 18:57 UTC, merged