Create New Bert example using Goemotions
deepjavalibrary/djl pull request #1682
Opened 2022-05-29 08:55 UTC by Konata-CG

## Description ##

* Create a new example of training the BERT model with the Goemotions dataset
* Closed #191

2022-05-30 15:56 UTC, frankfliu approved these changes

2022-05-30 16:24 UTC, lanking520 requested changes
As informed by author offline, this PR is still WIP

2022-05-31 18:37 UTC, zachgk commented
@Konata-CG Since @lanking520 mentioned that this PR is still WIP, I changed it to a draft PR which is GitHub's way to represent WIP PRs

2022-08-12 21:26 UTC, lanking520 approved these changes

2022-08-12 21:26 UTC, merged