[timeseries] add some basic block and deepAR model
deepjavalibrary/djl pull request #2027
Opened 2022-09-19 08:33 UTC by Carkham

## Description ##

This PR adds two new sections for creating trainable models.

The first part is embedding and scaler, which are responsible for encoding the input features and scaling the target values.

The second part is that we implemented a **deepAR** network model with the above-mentioned blcok, which refers to the implementation in [gluonTS](https://ts.gluon.ai/stable/api/gluonts/gluonts.mx.distribution.html). 

Since the model predicts a probability distribution, we need to override the different forward methods when training and inference with different block.

2022-10-26 18:39 UTC, frankfliu requested changes

2022-10-26 18:39 UTC, frankfliu commented on extensions/timeseries/src/main/java/ai/djl/timeseries/block/FeatureEmbedder.java
> +package ai.djl.timeseries.block;
Please add unit test

2022-10-28 09:08 UTC, Carkham commented on extensions/timeseries/src/main/java/ai/djl/timeseries/block/FeatureEmbedder.java
> +package ai.djl.timeseries.block;
Got it.

2022-10-28 15:27 UTC, frankfliu approved these changes

2022-10-28 15:27 UTC, merged